name: Publish Mod to Thunderstore.io

# Run publish action when a new release is... released
on:
  release:
    types: [published]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get version number
        run: echo "cleanVersion=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
      - name: Verify version number
        run: |
          manifestVersion=$(grep -oP '"version_number": "\K[^"]*' manifest.json)
          if [[ "$manifestVersion" != "${{ env.cleanVersion }}" ]]; then
            echo "Version mismatch!"
            echo "Tag version: ${{ env.cleanVersion }}"
            echo "manifest.json version: $manifestVersion"
            exit 1
          fi

  publish:
    runs-on: ubuntu-latest
    needs: verify
    steps:
      # Use checkout to publish the files in your repo
      - uses: actions/checkout@v3
      - uses: GreenTF/upload-thunderstore-package@v4.2
        with:
          namespace: "PoundTown" # the thunderstore team name
          description: Modpackage for trve warriors. Be Aggressive. # the description of the package
          token: ${{ secrets.thunderstore_svc }} # the thunderstore token, managed via secrets
          name: pt_valheim # the name of the package, can also use env.name var
          version: ${{ github.ref_name }} # Use the tag as the package version
          community: valheim # the game the package belongs to
          repo: valheim.thunderstore.io # the repo the package belongs to on thunderstore
          categories: | # <-- notice this pipe character
            modpacks

  notify-discord:
    runs-on: ubuntu-latest
    needs: publish
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Github Releases To Discord
        uses: SethCohen/github-releases-to-discord@v1.13.1
        with:
          webhook_url: ${{ secrets.WEBHOOK_URL }} # Discord webhook URL in secrets
          color: "2105893" # Hex color code for the embed
          username: "FrelseVíkingr" # bot username
          avatar_url: "https://github.com/lxhwes/pt-valheim/blob/main/docs/img/avatar.png" # bot avatar url
          content: "**A new version of pt-valheim has been released y'all**" # message content
          footer_title: "Changelog" # footer title
          footer_timestamp: true # show timestamp in footer (boolean)