name: Publish Mod to Thunderstore.io

# Run publish action when a new release is... released
on:
  release:
    types: [published]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get version number
        run: echo "cleanVersion=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Verify version number
        run: |
          manifestVersion=$(grep -oP '"version_number": "\K[^"]*' manifest.json)
          if [[ "$manifestVersion" != "${{ env.cleanVersion }}" ]]; then
            echo "Version mismatch!"
            echo "Tag version: ${{ env.cleanVersion }}"
            echo "manifest.json version: $manifestVersion"
            exit 1
          fi
  publish:
    runs-on: ubuntu-latest
    steps:
      # Use checkout to publish the files in your repo
      - uses: actions/checkout@v3
      - uses: GreenTF/upload-thunderstore-package@v4.2
        with:
          namespace: 'PoundTown' # the thunderstore team name
          description: Modpackage for trve warriors. Be Aggressive. # the description of the package
          token: ${{ secrets.thunderstore_svc }} # the thunderstore token, managed via secrets
          name: pt_valheim # the name of the package, can also use env.name var
          version: ${{ github.ref_name }} # Use the tag as the package version
          community: Valheim # the game the package belongs to
          repo: valheim.thunderstore.io # the repo the package belongs to on thunderstore
          categories: | # <-- notice this pipe character
            modpacks
